const DB = {
    TRANSLATIONS: {
        en: {
            app_title: "DISTORTION CORP",
            login_sub: "SECURE ACCESS TERMINAL v9.4",
            login_opt: ">> TERMINAL OPTIMIZED FOR DESKTOP DISPLAY",
            login_placeholder: "ENTER_ACCESS_CODE...",
            login_verifying: "VERIFYING CREDENTIALS...",
            access_granted: "ACCESS GRANTED",
            os_connected: "DISTORTION_OS // CONNECTED",
            ui_mode_desktop: "VIEW: DESKTOP",
            ui_mode_mobile: "VIEW: MOBILE",
            btn_system: "SYSTEM",
            btn_rotate: "ROTATE",
            btn_visit: "[ VISIT LINK ]",
            btn_email: "[ SEND TRANSMISSION ]",
            btn_guidelines: "[ VIEW GUIDELINES ]",
            btn_where_to_buy: "[ WHERE TO ACQUIRE ]",
            btn_event_site: "[ EVENT WEBSITE ]",
            btn_booth_map: "[ BOOTH MAP ]",
            btn_sort_tarot: "[ SORT: TAROT ]",
            btn_sort_name: "[ SORT: A-Z ]",
            btn_view_all: "[ VIEW: ALL ]",
            btn_check_events: "[ VIEW EVENT SCHEDULE ]",
            btn_scale_normal: "SIZE: NORMAL",
            btn_scale_large: "SIZE: LARGE",
            sig_hash: "HASH",
            sig_ping: "PING",

            icon_overview: "PROJECT_BRIEF.LOG",
            icon_archive: "FIRST LIGHT: ARCHIVE_DB.EXE",
            icon_employees: "EMPLOYEE_DB.EXE",
            icon_shop: "EVENT_LOG.TXT",
            icon_comm: "COMMUNICATION.EXE",
            icon_tos: "TERMS_OF_SERVICE.TXT",
            icon_settings: "SYSTEM_SETTINGS.EXE",
            icon_assistant: "ASSISTANT_AI.EXE",
            icon_interest: "INTEREST_CHECK.EXE",

            win_overview: "PROJECT_BRIEF.LOG",
            win_archive: "FIRST LIGHT: ARCHIVE_DB.EXE",
            win_employees: "EMPLOYEE_DB.EXE",
            win_shop: "EVENT_LOG.TXT",
            win_comm: "COMMUNICATION.EXE",
            win_tos: "TERMS_OF_SERVICE.TXT",
            win_settings: "SYSTEM_SETTINGS.EXE",
            win_interest: "INTEREST_CHECK.EXE",

            overview_title: "DISTORTION DIVINA",
            overview_label_goal: "GOAL",
            overview_text_1: "Distortion Divina is an unofficial fan project inspired by the worlds of Project Moon and Project Mili. Our dream is to build a collectible, tarot-inspired card game- created by fans, for fans.",
            overview_label_plan: "PLAN",
            overview_text_plan: "We are building this vision in phases. Our first chapter, First Light, is dedicated to proving our creative process. Our priority right now is simply to deliver stunning, high-quality illustrations that pay proper homage to the source material.",
            overview_label_acquisition: "ACQUISITION",
            overview_text_acquisition: "First Light packs will be available exclusively at upcoming offline events. Check our schedule for locations.",
            overview_text_note: "This is a passion project currently running on personal funds. Every penny of profit goes directly to our amazing artists and brings us one step closer to the full game. We hope you'll join us on this journey.",
            brief_id: "ID: 001-GENESIS-DIVINA",
            brief_clearance: "CLEARANCE: PUBLIC",
            brief_fig_main: "FIG_0: PROJECT_CONCEPT",
            brief_fig_a: "FIG_A: CONCEPT_VISUALIZATION",
            brief_fig_b: "FIG_B: CARD_BACK_DESIGN",
            brief_fig_c: "FIG_C: EVENT_MOCKUP",
            brief_fig_d: "FIG_D: PRODUCT_SAMPLE",
            brief_sys_notes_label: "> SYSTEM NOTES:",
            brief_sys_notes: "The \"First Light\" initiative is currently active. All personnel are advised to review the Archive DB for drop rates.",

            archive_title: "FIRST LIGHT",
            archive_desc: "The initial manifestation. A collection of archetypes emerging from the distortion. Witness the beginning of the reconstruction.",
            archive_dist_proto_label: ">> DISTRIBUTION PROTOCOL:",
            archive_dist_proto: "First Light is distributed in sealed packs of 5 cards (4 Normal, 1 Holographic). Contents are randomized by the system; individual selection is not permitted. May the luck of the draw be with you.",
            archive_status: "> LOADING ASSETS... COMPLETE",
            rates_title: "PACK CONFIGURATION",
            rates_content_holo: "1x HOLOGRAPHIC",
            rates_content_norm: "4x NORMAL",
            rates_total_count: "Total: 9 Holo / 29 Normal",
            rates_drop_title: "DROP RATES (PER SLOT)",
            rates_holo_label: "SPECIFIC HOLO",
            rates_norm_label: "SPECIFIC NORMAL",

            selector_prefix: "SELECT: ",
            selector_sub: "Multiple data streams detected. Select a timeline to view.",

            viewer_title: "ARTIFACT_VIEWER.EXE",
            viewer_asset_id: "ID:",
            viewer_artist_label: "EMPLOYEE DATA",
            viewer_char_label: "CHARACTER",
            viewer_illus_label: "ILLUSTRATOR",
            viewer_no_variant: "No variant data linked.",

            employees_header: "PERSONNEL DATABASE",
            emp_accessing: "> ACCESSING TEAM RECORDS...",
            th_no: "NO.",
            th_card: "CARD",
            th_char: "CHARACTER",
            th_emp: "EMPLOYEES",
            th_pen: "PEN NAME",
            th_role: "ROLE",

            shop_header: "UPCOMING EVENTS",
            event_1_title: "LUNATIC MOONLIGHT EVENT",
            event_1_loc: "LOCATION: TOKYO",
            event_1_booth: "BOOTH: A14 (DISTORTION CORP)",
            event_1_time: "TIME: 11:30 - 16:00",
            event_1_date: "15 FEB 2026",
            event_2_title: "ONE MILLION MOON CONCERT",
            event_2_loc: "LOCATION: JAPAN",
            event_2_date: "21 FEB 2026",
            event_3_title: "ONLINE STORE OPENING",
            event_3_desc: "STATUS: COMING SOON",

            comm_header: "SECURE UPLINKS",
            comm_twitter: "TWITTER // X",
            comm_sub_twitter: "> ENCRYPTED FEED ESTABLISHED",
            comm_discord: "DISCORD SERVER",
            comm_sub_discord: "> SECURE CHANNEL OPEN",
            comm_email: "EMAIL UPLINK",
            comm_sub_email: "> DIRECT FREQUENCY OPEN",
            comm_admin: "ADMIN DIRECT LINE",
            comm_sub_admin_1: "> OVERSEER: oober",
            comm_sub_admin_2: "\"Feel free to add and ask me any questions.\"",

            settings_header: "CONFIGURATION",
            lang_select: "LANGUAGE PROTOCOL",
            settings_note: "> SYSTEM UPDATE: IMMEDIATE\n> REBOOT NOT REQUIRED",
            settings_disclaimer: "> NOTICE: Localization is approximate and may contain deviations.",

            tos_header: "TERMS OF SERVICE",
            tos_content: "Distortion Divina is an unofficial fan project inspired by the worlds of Project Moon and Project Mili. All rights belong to the individual owners and artists.",
            tos_guidelines_header: "OFFICIAL GUIDELINES",
            tos_pm: "PROJECT MOON",
            tos_mili: "PROJECT MILI",

            interest_header: "INTEREST CHECK FORM",
            interest_desc: "Please indicate your interest in purchasing First Light packs. This data will be used to determine print run quantities.",
            btn_interest: "[ OPEN FORM ]",

            time_days: "D",
            time_hours: "H",
            time_mins: "M",
            time_secs: "S",
            time_tminus: "T-MINUS",
            time_concluded: "STATUS: CONCLUDED",

            assistant_steps: [
                "Welcome, Agent. I am OOBOT. I can guide you through the archive.",
                "Click the desktop icons to access classified files. 'PROJECT_BRIEF' contains your mission objectives.",
                "Use 'EMPLOYEE_DB' to view the team roster.",
                "Use 'ARCHIVE_DB' to inspect the tarot artifacts. Click any file to analyze metadata.",
                "Check 'EVENT_LOG' for upcoming timeline incursions and store openings.",
                "Secure communication channels are available in 'COMMUNICATION.EXE'.",
                "You can drag windows to organize your workspace. Good luck."
            ],
            cat_lines: [
                "Prrr...",
                "Meow.",
                "Feed me milk.",
                "This is IDEAL.",
                "The distortion purrs...",
                "*Stares intently*",
                "3.14159265359",
                "System normal. Let me out.",
                "Do not touch the screen too hard."
            ],
            cat_hiss: "HISS!",
            cat_meow: "Meow?"
        },
        ko: {
            app_title: "디스토션 코퍼레이션",
            login_sub: "보안 액세스 터미널 v9.4",
            login_opt: ">> 데스크톱 디스플레이에 최적화된 터미널",
            login_placeholder: "액세스_코드_입력...",
            login_verifying: "자격 증명 확인 중...",
            access_granted: "액세스 허가됨",
            os_connected: "디스토션_OS // 연결됨",
            ui_mode_desktop: "보기: 데스크톱",
            ui_mode_mobile: "보기: 모바일",
            btn_system: "시스템",
            btn_rotate: "회전",
            btn_visit: "[ 링크 방문 ]",
            btn_email: "[ 전송 보내기 ]",
            btn_guidelines: "[ 가이드라인 보기 ]",
            btn_where_to_buy: "[ 획득처 확인 ]",
            btn_event_site: "[ 이벤트 웹사이트 ]",
            btn_booth_map: "[ 부스 맵 ]",
            btn_sort_tarot: "[ 정렬: 타로 ]",
            btn_sort_name: "[ 정렬: 이름순 ]",
            btn_view_all: "[ 보기: 전체 ]",
            btn_check_events: "[ 이벤트 일정 보기 ]",
            btn_scale_normal: "크기: 보통",
            btn_scale_large: "크기: 크게",
            sig_hash: "해시",
            sig_ping: "지연시간",

            icon_overview: "프로젝트_브리핑.LOG",
            icon_archive: "FIRST LIGHT: 아카이브_DB.EXE",
            icon_employees: "직원_DB.EXE",
            icon_shop: "이벤트_로그.TXT",
            icon_comm: "통신.EXE",
            icon_tos: "이용_약관.TXT",
            icon_settings: "시스템_설정.EXE",
            icon_assistant: "어시스턴트_AI.EXE",
            icon_interest: "수요_조사.EXE",

            win_overview: "프로젝트_브리핑.LOG",
            win_archive: "FIRST LIGHT: 아카이브_DB.EXE",
            win_employees: "직원_DB.EXE",
            win_shop: "이벤트_로그.TXT",
            win_comm: "통신.EXE",
            win_tos: "이용_약관.TXT",
            win_settings: "시스템_설정.EXE",
            win_interest: "수요_조사.EXE",

            overview_title: "디스토션 디비나",
            overview_label_goal: "목표",
            overview_text_1: "Distortion Divina는 Project Moon과 Project Mili의 세계에서 영감을 받은 비공식 팬 프로젝트입니다. 우리의 꿈은 팬들에 의해, 팬들을 위해 만들어진 수집 가능한 타로 카드 게임을 만드는 것입니다.",
            overview_label_plan: "계획",
            overview_text_plan: "우리는 이 비전을 단계별로 구축하고 있습니다. 첫 번째 장인 'First Light'는 우리의 창작 과정을 증명하는 데 전념합니다. 현재 우리의 우선순위는 원작에 경의를 표하는 고품질의 일러스트레이션을 제공하는 것입니다.",
            overview_label_acquisition: "획득",
            overview_text_acquisition: "First Light 팩은 향후 오프라인 이벤트에서 독점적으로 판매될 예정입니다. 일정에서 위치를 확인하세요.",
            overview_text_note: "이것은 개인 자금으로 운영되는 열정 프로젝트입니다. 모든 수익금은 훌륭한 아티스트들에게 직접 전달되며, 정식 게임 제작에 한 걸음 더 다가가는 데 사용됩니다.",
            brief_id: "ID: 001-GENESIS-DIVINA",
            brief_clearance: "보안 등급: 공개",
            brief_fig_main: "그림_0: 프로젝트_컨셉",
            brief_fig_a: "그림_A: 컨셉_시각화",
            brief_fig_b: "그림_B: 카드_뒷면_디자인",
            brief_fig_c: "그림_C: 이벤트_목업",
            brief_fig_d: "그림_D: 제품_샘플",
            brief_sys_notes_label: "> 시스템 참고:",
            brief_sys_notes: "\"First Light\" 이니셔티브가 현재 활성화되어 있습니다. 모든 요원은 아카이브 DB에서 드롭률을 확인하십시오.",

            archive_title: "FIRST LIGHT",
            archive_desc: "최초의 현현. 왜곡에서 솟아오른 아키타입들의 모음. 재구축의 시작을 목격하십시오.",
            archive_dist_proto_label: ">> 배포 프로토콜:",
            archive_dist_proto: "First Light는 5장의 카드가 들어있는 밀봉된 팩으로 배포됩니다 (노멀 4장, 홀로그래픽 1장). 내용물은 시스템에 의해 무작위로 결정되며, 개별 선택은 허용되지 않습니다.",
            archive_status: "> 에셋 로드 중... 완료",
            rates_title: "팩 구성",
            rates_content_holo: "1x 홀로그래픽",
            rates_content_norm: "4x 노멀",
            rates_total_count: "총합: 홀로 9종 / 노멀 29종",
            rates_drop_title: "드롭률 (슬롯당)",
            rates_holo_label: "특정 홀로",
            rates_norm_label: "특정 노멀",

            selector_prefix: "선택: ",
            selector_sub: "여러 데이터 스트림이 감지되었습니다. 볼 타임라인을 선택하십시오.",

            viewer_title: "아티팩트_뷰어.EXE",
            viewer_asset_id: "ID:",
            viewer_artist_label: "직원 데이터",
            viewer_char_label: "캐릭터",
            viewer_illus_label: "일러스트레이터",
            viewer_no_variant: "연결된 변체 데이터가 없습니다.",

            employees_header: "인사 데이터베이스",
            emp_accessing: "> 팀 기록 액세스 중...",
            th_no: "번호",
            th_card: "카드",
            th_char: "캐릭터",
            th_emp: "아티스트",
            th_pen: "필명",
            th_role: "역할",

            shop_header: "예정된 이벤트",
            event_1_title: "LUNATIC MOONLIGHT 이벤트",
            event_1_loc: "장소: 도쿄",
            event_1_booth: "부스: A14 (DISTORTION CORP)",
            event_1_time: "시간: 11:30 - 16:00",
            event_1_date: "2026년 2월 15일",
            event_2_title: "ONE MILLION MOON 콘서트",
            event_2_loc: "장소: 일본",
            event_2_date: "2026년 2월 21일",
            event_3_title: "온라인 스토어 오픈",
            event_3_desc: "상태: 출시 예정",

            comm_header: "보안 업링크",
            comm_twitter: "트위터 // X",
            comm_sub_twitter: "> 암호화된 피드 연결됨",
            comm_discord: "디스코드 서버",
            comm_sub_discord: "> 보안 채널 개방됨",
            comm_email: "이메일 업링크",
            comm_sub_email: "> 직접 주파수 개방됨",
            comm_admin: "관리자 직통 라인",
            comm_sub_admin_1: "> 감독관: oober",
            comm_sub_admin_2: "\"언제든지 추가해서 궁금한 점을 물어보세요.\"",

            settings_header: "환경 설정",
            lang_select: "언어 프로토콜",
            settings_note: "> 시스템 업데이트: 즉시\n> 재부팅 불필요",
            settings_disclaimer: "> 주의: 번역은 근사치이며 오차가 있을 수 있습니다.",

            tos_header: "이용 약관",
            tos_content: "Distortion Divina는 Project Moon과 Project Mili의 세계에서 영감을 받은 비공식 팬 프로젝트입니다. 모든 권리는 개별 소유자와 아티스트에게 있습니다.",
            tos_guidelines_header: "공식 가이드라인",
            tos_pm: "프로젝트 문",
            tos_mili: "프로젝트 밀리",

            interest_header: "수요 조사 양식",
            interest_desc: "First Light 팩 구매 의향을 표시해 주십시오. 이 데이터는 인쇄 수량을 결정하는 데 사용됩니다.",
            btn_interest: "[ 양식 열기 ]",

            time_days: "일",
            time_hours: "시",
            time_mins: "분",
            time_secs: "초",
            time_tminus: "남은 시간",
            time_concluded: "상태: 종료됨",

            assistant_steps: [
                "환영합니다, 요원님. 저는 OOBOT입니다. 아카이브 안내를 도와드리겠습니다.",
                "데스크톱 아이콘을 클릭하여 기밀 파일에 액세스하십시오. 'PROJECT_BRIEF'에 미션 목표가 포함되어 있습니다.",
                "팀 명단을 보려면 'EMPLOYEE_DB'를 사용하십시오.",
                "타로 유물을 조사하려면 'ARCHIVE_DB'를 사용하십시오. 메타데이터를 분석하려면 파일을 클릭하십시오.",
                "다가오는 타임라인 침입과 스토어 오픈 소식은 'EVENT_LOG'를 확인하십시오.",
                "창을 드래그하여 작업 공간을 구성할 수 있습니다. 행운을 빕니다."
            ],
            cat_lines: [
                "골골골...",
                "야옹.",
                "우유 줘.",
                "이것은 이상(IDEAL)적이야.",
                "왜곡이 가르랑거리네...",
                "*빤히 쳐다봄*",
                "3.14159265359",
                "시스템 정상. 날 내보내 줘.",
                "화면을 너무 세게 만지지 마."
            ],
            cat_hiss: "하악!",
            cat_meow: "야옹?"
        },
        ja: {
            app_title: "ディストーション・コーポレーション",
            login_sub: "セキュアアクセス端末 v9.4",
            login_opt: ">> デスクトップ表示に最適化された端末",
            login_placeholder: "アクセスコードを入力...",
            login_verifying: "資格情報を確認中...",
            access_granted: "アクセス許可",
            os_connected: "ディストーション_OS // 接続済み",
            ui_mode_desktop: "表示: デスクトップ",
            ui_mode_mobile: "表示: モバイル",
            btn_system: "システム",
            btn_rotate: "回転",
            btn_visit: "[ リンクを開く ]",
            btn_email: "[ 送信 ]",
            btn_guidelines: "[ ガイドラインを見る ]",
            btn_where_to_buy: "[ 入手場所を確認 ]",
            btn_event_site: "[ イベントサイト ]",
            btn_booth_map: "[ ブースマップ ]",
            btn_sort_tarot: "[ ソート: タロー ]",
            btn_sort_name: "[ ソート: 名前順 ]",
            btn_view_all: "[ 表示: すべて ]",
            btn_check_events: "[ イベント日程を見る ]",
            btn_scale_normal: "サイズ: 標準",
            btn_scale_large: "サイズ: 大",
            sig_hash: "ハッシュ",
            sig_ping: "ピング",

            icon_overview: "プロジェクト概要.LOG",
            icon_archive: "FIRST LIGHT: アーカイブ_DB.EXE",
            icon_employees: "従業員_DB.EXE",
            icon_shop: "イベントログ.TXT",
            icon_comm: "通信.EXE",
            icon_tos: "利用規約.TXT",
            icon_settings: "システム設定.EXE",
            icon_assistant: "アシスタント_AI.EXE",
            icon_interest: "興味調査.EXE",

            win_overview: "プロジェクト概要.LOG",
            win_archive: "FIRST LIGHT: アーカイブ_DB.EXE",
            win_employees: "従業員_DB.EXE",
            win_shop: "イベントログ.TXT",
            win_comm: "通信.EXE",
            win_tos: "利用規約.TXT",
            win_settings: "システム設定.EXE",
            win_interest: "興味調査.EXE",

            overview_title: "ディストーション・ディヴィナ",
            overview_label_goal: "目標",
            overview_text_1: "Distortion Divinaは、Project MoonとProject Miliの世界にインスパイアされた非公式ファンプロジェクトです。私たちの夢は、ファンの手によって、ファンのために作られたタロットカードゲームを構築することです。",
            overview_label_plan: "計画",
            overview_text_plan: "私たちは段階的にこのビジョンを構築しています。最初の章「First Light」は、私たちの制作プロセスを証明することに専念しています。現在の優先事項は、原作に敬意を表した高品質なイラストを提供することです。",
            overview_label_acquisition: "入手方法",
            overview_text_acquisition: "First Lightパックは、今後のオフラインイベントで独占的に販売される予定です。場所はスケジュールを確認してください。",
            overview_text_note: "これは個人資金で運営されている情熱プロジェクトです。収益はすべて素晴らしいアーティストたちに直接還元され、フルゲームの制作に一歩近づきます。",
            brief_id: "ID: 001-GENESIS-DIVINA",
            brief_clearance: "クリアランス: 公開",
            brief_fig_main: "図_0: プロジェクトコンセプト",
            brief_fig_a: "図_A: コンセプト視覚化",
            brief_fig_b: "図_B: カード背面デザイン",
            brief_fig_c: "図_C: イベントモックアップ",
            brief_fig_d: "図_D: 製品サンプル",
            brief_sys_notes_label: "> システム注記:",
            brief_sys_notes: "「First Light」イニシアチブが現在有効です。全要員はアーカイブDBでドロップ率を確認してください。",

            archive_title: "FIRST LIGHT",
            archive_desc: "最初の現れ。歪みから立ち上がるアルケタイプのコレクション。再構築の始まりを目撃せよ。",
            archive_dist_proto_label: ">> 配布プロトコル:",
            archive_dist_proto: "First Lightは5枚入りの密封パック（ノーマル4枚、ホログラフィック1枚）で配布されます。内容はシステムによってランダムに決定され、個別の選択は許可されません。",
            archive_status: "> アセット読み込み中... 完了",
            rates_title: "パック構成",
            rates_content_holo: "1x ホログラフィック",
            rates_content_norm: "4x ノーマル",
            rates_total_count: "合計: ホロ 9種 / ノーマル 29種",
            rates_drop_title: "ドロップ率 (スロット毎)",
            rates_holo_label: "特定のホロ",
            rates_norm_label: "特定のノーマル",

            selector_prefix: "選択: ",
            selector_sub: "複数のデータストリームが検出されました。表示するタイムラインを選択してください。",

            viewer_title: "アーティファクトビューア.EXE",
            viewer_asset_id: "ID:",
            viewer_artist_label: "従業員データ",
            viewer_char_label: "キャラクター",
            viewer_illus_label: "イラストレーター",
            viewer_no_variant: "関連付けられたバリアントデータがありません。",

            employees_header: "職員データベース",
            emp_accessing: "> チーム記録にアクセス中...",
            th_no: "NO.",
            th_card: "カード",
            th_char: "キャラクター",
            th_emp: "アーティスト",
            th_pen: "ペンネーム",
            th_role: "役割",

            shop_header: "今後のイベント",
            event_1_title: "LUNATIC MOONLIGHT イベント",
            event_1_loc: "場所: 東京",
            event_1_booth: "ブース: A14 (DISTORTION CORP)",
            event_1_time: "時間: 11:30 - 16:00",
            event_1_date: "2026年 2月 15日",
            event_2_title: "ONE MILLION MOON コンサート",
            event_2_loc: "場所: 日本",
            event_2_date: "2026년 2월 21일",
            event_3_title: "オンラインストア開店",
            event_3_desc: "ステータス: 近日公開",

            comm_header: "セキュアアップリンク",
            comm_twitter: "ツイッター // X",
            comm_sub_twitter: "> 暗号化フィード接続済み",
            comm_discord: "ディスコードサーバー",
            comm_sub_discord: "> セキュアチャンネル開放中",
            comm_email: "メールアップリンク",
            comm_sub_email: "> 直接周波数開放中",
            comm_admin: "管理官直通",
            comm_sub_admin_1: "> 監督官: oober",
            comm_sub_admin_2: "「気軽に追加して、質問してください。」",

            settings_header: "設定",
            lang_select: "言語プロトコル",
            settings_note: "> システムアップデート: 即時\n> 再起動不要",
            settings_disclaimer: "> 注意: 翻訳は概算であり、誤差が含まれる場合があります。",

            tos_header: "利用規約",
            tos_content: "Distortion Divinaは、Project MoonとProject Miliの世界にインスパイアされた非公式ファンプロジェクトです。すべての権利は個々の所有者とアーティストに帰属します。",
            tos_guidelines_header: "公式ガイドライン",
            tos_pm: "プロジェクト・ムーン",
            tos_mili: "プロジェクト・ミリ",

            interest_header: "興味調査フォーム",
            interest_desc: "First Lightパックの購入希望についてお知らせください。このデータは印刷部数の決定に使用されます。",
            btn_interest: "[ フォームを開く ]",

            time_days: "日",
            time_hours: "時",
            time_mins: "分",
            time_secs: "秒",
            time_tminus: "残り時間",
            time_concluded: "ステータス: 終了",

            assistant_steps: [
                "ようこそ、エージェント。私はOOBOTです。アーカイブの案内をいたします。",
                "デスクトップアイコンをクリックして機密ファイルにアクセスしてください。「PROJECT_BRIEF」にミッションの目的が記されています。",
                "チームの名簿を見るには「EMPLOYEE_DB」を使用してください。",
                "タロットの遺物を調査するには「ARCHIVE_DB」を使用してください。ファイルを主リックしてメタデータを分析できます。",
                "今後のタイムライン侵入や開店情報は「EVENT_LOG」を確認してください。",
                "ウィンドウをドラッグしてワークスペースを整理できます。幸運を祈ります。"
            ],
            cat_lines: [
                "ゴロゴロ...",
                "ニャー。",
                "ミルクをくれ。",
                "これは「理想(IDEAL)」的だ。",
                "歪みが喉を鳴らしている...",
                "*じっと見つめる*",
                "3.14159265359",
                "システム正常。外に出してくれ。",
                "画面を強く触りすぎないで。"
            ],
            cat_hiss: "シャー！",
            cat_meow: "ニャー？"
        }
    },
    CARDS: [
        { id: 0, title: { en: "0. THE FOOL", ko: "0. 광대", ja: "0. 愚者" }, description: { en: "The beginning of a journey. Infinite potential and naivety.", ko: "여정의 시작. 무한한 잠재력과 순진함.", ja: "旅の始まり。無限の可能性と無邪気さ。" }, image: "./images/CruKz4f.png" },
        { id: 1, title: { en: "I. THE MAGICIAN", ko: "I. 마법사", ja: "I. 魔術師" }, description: { en: "Manifestation, resourcefulness, power, inspired action.", ko: "현현, 지략, 힘, 영감받은 행동.", ja: "具現化、機転、力、インスピレーションによる行動。" }, image: "./images/uAQ9Pgs.png" },
        { id: 2, title: { en: "II. THE HIGH PRIESTESS", ko: "II. 고위 여사제", ja: "II. 女教皇" }, description: { en: "Intuition, sacred knowledge, divine feminine, the subconscious mind.", ko: "직관, 신성한 지식, 신성한 여성성, 잠재의식.", ja: "直感、神聖な知識、神聖な女性性、潜在意識。" }, image: "./images/soI92lN.png" },
        { id: 3, title: { en: "III. THE EMPRESS", ko: "III. 여황제", ja: "III. 女帝" }, description: { en: "Femininity, beauty, nature, nurturing, abundance.", ko: "여성성, 아름다움, 자연, 양육, 풍요.", ja: "女性性、美、自然、育み、豊かさ。" }, image: "./images/1dfh7kg.png" },
        { id: 4, title: { en: "IV. THE EMPEROR", ko: "IV. 황제", ja: "IV. 皇帝" }, description: { en: "Authority, establishment, structure, a father figure.", ko: "권위, 설립, 구조, 아버지의 상.", ja: "権威、設立、構造、父性。" }, image: "./images/YJIANCf.png" },
        { id: 5, title: { en: "V. THE HIEROPHANT", ko: "V. 교황", ja: "V. 法王" }, description: { en: "Spiritual wisdom, religious beliefs, conformity, tradition, institutions.", ko: "영적 지혜, 종교적 신념, 순응, 전통, 제도.", ja: "精神的な知恵、宗教的信念、順応、伝統、制度。" }, image: "./images/LP9oHvK.png" },
        { id: 6, title: { en: "VI. THE LOVERS", ko: "VI. 연인", ja: "VI. 恋人" }, description: { en: "Love, harmony, relationships, values alignment, choices.", ko: "사랑, 조화, 관계, 가치관의 일치, 선택.", ja: "愛、調和、関係、価値観の一致、選択。" }, image: "./images/OC3UCop.png" },
        { id: 7, title: { en: "VII. THE CHARIOT", ko: "VII. 전차", ja: "VII. 戦車" }, description: { en: "Control, willpower, success, action, determination.", ko: "통제, 의지력, 성공, 행동, 결단력.", ja: "制御、意志力、成功、行動、決意。" }, image: "./images/ABIRnnJ.png" },
        { id: 8, title: { en: "VIII. STRENGTH", ko: "VIII. 힘", ja: "VIII. 力" }, description: { en: "Strength, courage, persuasion, influence, compassion.", ko: "힘, 용기, 설득, 영향력, 연민.", ja: "力、勇気、説得、影響力、思いやり。" }, image: "./images/LLDHPbO.png" },
        { id: 9, title: { en: "IX. THE HERMIT", ko: "IX. 은둔자", ja: "IX. 隠者" }, description: { en: "Soul-searching, introspection, being alone, inner guidance.", ko: "자아 성찰, 내면 탐구, 고독, 내면의 인도.", ja: "自己探求、内省、孤独、内なる導き。" }, image: "./images/58dju1b.png" },
        { id: 10, title: { en: "X. WHEEL OF FORTUNE", ko: "X. 운명의 수레바퀴", ja: "X. 運命の輪" }, description: { en: "Good luck, karma, life cycles, destiny, a turning point.", ko: "행운, 카르마, 인생의 순환, 운명, 전환점.", ja: "幸運、カルマ、人生のサイクル、運命、転換点。" }, image: "./images/wHrQNdi.png" },
        { id: 11, title: { en: "XI. JUSTICE", ko: "XI. 정의", ja: "XI. 正義" }, description: { en: "Justice, fairness, truth, cause and effect, law.", ko: "정의, 공정함, 진실, 인과 관계, 법.", ja: "正義、公平、真実、因果関係、法。" }, image: "./images/yN6qpDP.png" },
        { id: 12, title: { en: "XII. THE HANGED MAN", ko: "XII. 매달린 사람", ja: "XII. 吊るされた男" }, description: { en: "Pause, surrender, letting go, new perspectives.", ko: "일시 정지, 항복, 놓아줌, 새로운 관점.", ja: "一時停止、降伏、手放すこと、新しい視点。" }, image: "./images/WpNP759.png" },
        { id: 13, title: { en: "XIII. DEATH", ko: "XIII. 죽음", ja: "XIII. 死神" }, description: { en: "Endings, change, transformation, transition.", ko: "끝, 변화, 변형, 과도기.", ja: "終わり、変化、変容、移行。" }, image: "./images/AWduZSc.png" },
        { id: 14, title: { en: "XIV. TEMPERANCE", ko: "XIV. 절제", ja: "XIV. 節制" }, description: { en: "Balance, moderation, patience, purpose.", ko: "균형, 절제, 인내, 목적.", ja: "バランス、節度、忍耐、目的。" }, image: "./images/mxQfyDY.png" },
        { id: 15, title: { en: "XV. THE DEVIL", ko: "XV. 악마", ja: "XV. 悪魔" }, description: { en: "Shadow self, attachment, addiction, restriction, sexuality.", ko: "그림자 자아, 애착, 중독, 구속, 성욕.", ja: "影の自己、執着、中毒、束縛、セクシュアリティ。" }, image: "./images/R0Z9FuO.png" },
        { id: 16, title: { en: "XVI. THE TOWER", ko: "XVI. 탑", ja: "XVI. 塔" }, description: { en: "Sudden change, upheaval, chaos, revelation, awakening.", ko: "갑작스러운 변화, 격변, 혼란, 계시, 각성.", ja: "突然の変化、激変、混沌、啓示、覚醒。" }, image: "./images/iimtseT.png" },
        { id: 17, title: { en: "XVII. THE STAR", ko: "XVII. 별", ja: "XVII. 星" }, description: { en: "Hope, faith, purpose, renewal, spirituality.", ko: "희망, 믿음, 목적, 갱신, 영성.", ja: "希望、信仰、目的、再生、精神性。" }, image: "./images/4W0AQoS.png" },
        { id: 18, title: { en: "XVIII. THE MOON", ko: "XVIII. 달", ja: "XVIII. 月" }, description: { en: "Illusion, fear, anxiety, subconscious, intuition.", ko: "환상, 두려움, 불안, 잠재의식, 직관.", ja: "幻想、恐怖、不安、潜在意識、直感。" }, image: "./images/yklk4pi.png" },
        { id: 19, title: { en: "XIX. THE SUN", ko: "XIX. 태양", ja: "XIX. 太陽" }, description: { en: "Positivity, fun, warmth, success, vitality.", ko: "긍정, 즐거움, 따뜻함, 성공, 활력.", ja: "前向き、楽しさ、暖かさ、成功、活力。" }, image: "./images/RhJpG3R.png" },
        { id: 20, title: { en: "XX. JUDGEMENT", ko: "XX. 심판", ja: "XX. 審判" }, description: { en: "Judgement, rebirth, inner calling, absolution.", ko: "심판, 부활, 내면의 부름, 사면.", ja: "審判、再生、内なる呼び声、赦し。" }, image: "./images/KWhQrYr.png" },
        { id: 21, title: { en: "XXI. THE WORLD", ko: "XXI. 세계", ja: "XXI. 世界" }, description: { en: "Completion, integration, accomplishment, travel.", ko: "완성, 통합, 성취, 여행.", ja: "完成、統合、達成、旅。" }, image: "./images/fYI05v5.png" }
    ],
    EMPLOYEES: [
        { cardId: 0, no: "0", card: "The Fool", char: { en: "Hod", ko: "호드", ja: "ホド" }, artist: "Herokatz", pen: "Herocatz", role: { en: "Main Illustrator", ko: "메인 일러스트레이터", ja: "メインイラストレーター" }, variantImage: "./images/CruKz4f.png", socials: { twitter: "https://x.com/AhoHeroCatz" } },
        { cardId: 1, no: "I", card: "The Magician", char: { en: "Malkuth", ko: "말쿠트", ja: "マルクト" }, artist: "Nolm", pen: "Nolm", role: { en: "Artist", ko: "일러스트레이터", ja: "イラストレーター" }, variantImage: "./images/Syy5Gkx.png", socials: { twitter: "https://x.com/nolm_zi" } },
        { cardId: 2, no: "II", card: "The High Priestess", char: { en: "Yi Sang", ko: "이상", ja: "イサン" }, artist: "Sik", pen: "Sik", role: { en: "Artist", ko: "일러스트레이터", ja: "イラストレーター" }, variantImage: "./images/uAQ9Pgs.png", socials: { twitter: "https://x.com/sik_limbus" } },
        { cardId: 3, no: "III", card: "The Empress", char: { en: "Ishmael", ko: "이스마엘", ja: "イシュメール" }, artist: "Mae", pen: "Mae", role: { en: "Artist", ko: "일러스트레이터", ja: "イラストレーター" }, variantImage: "./images/wHrQNdi.png", socials: { twitter: "https://x.com/mae_limbus" } },
        { cardId: 4, no: "IV", card: "The Emperor", char: { en: "Meursault", ko: "뫼르소", ja: "ムルソー" }, artist: "Dudler", pen: "Dudler", role: { en: "Artist", ko: "일러스트레이터", ja: "イラストレーター" }, variantImage: "./images/fYI05v5.png", socials: { twitter: "https://x.com/dudler_limbus" } },
        { cardId: 5, no: "V", card: "The Hierophant", char: { en: "Heathcliff", ko: "히스클리프", ja: "ヒースクリフ" }, artist: "Nokso", pen: "Nokso", role: { en: "Artist", ko: "일러스트레이터", ja: "イラストレーター" }, variantImage: "./images/YJIANCf.png", socials: { twitter: "https://x.com/nokso_limbus" } },
        { cardId: 6, no: "VI", card: "The Lovers", char: { en: "Catherine", ko: "캐서린", ja: "キャサリン" }, artist: "Viper", pen: "Viper", role: { en: "Artist", ko: "일러스트레이터", ja: "イラストレーター" }, variantImage: "./images/RhJpG3R.png", socials: { twitter: "https://x.com/viper_limbus" } },
        { cardId: 7, no: "VII", card: "The Chariot", char: { en: "Charon", ko: "카론", ja: "カロン" }, artist: "Bell", pen: "Bell", role: { en: "Artist", ko: "일러스트레이터", ja: "イラストレーター" }, variantImage: "./images/soI92lN.png", socials: { twitter: "https://x.com/bell_limbus" } },
        { cardId: 8, no: "VIII", card: "Strength", char: { en: "Don Quixote", ko: "돈키호테", ja: "ドンキホーテ" }, artist: "Moom", pen: "Moom", role: { en: "Artist", ko: "일러스트레이터", ja: "イラストレーター" }, variantImage: "./images/yN6qpDP.png", socials: { twitter: "https://x.com/moom_limbus" } },
        { cardId: 9, no: "IX", card: "The Hermit", char: { en: "Faust", ko: "파우스트", ja: "ファウスト" }, artist: "Kuro", pen: "Kuro", role: { en: "Artist", ko: "일러스트레이터", ja: "イラストレーター" }, variantImage: "./images/XEEn4Ee.png", socials: { twitter: "https://x.com/kuro_limbus" } },
        { cardId: 10, no: "X", card: "Wheel of Fortune", char: { en: "Hong Lu", ko: "홍루", ja: "ホンル" }, artist: "Rin", pen: "Rin", role: { en: "Artist", ko: "일러스트레이터", ja: "イラストレーター" }, variantImage: "./images/R0Z9FuO.png", socials: { twitter: "https://x.com/rin_limbus" } },
        { cardId: 11, no: "XI", card: "Justice", char: { en: "Sinclair", ko: "싱클레어", ja: "シンクレア" }, artist: "Hana", pen: "Hana", role: { en: "Artist", ko: "일러스트레이터", ja: "イラストレーター" }, variantImage: "./images/mxQfyDY.png", socials: { twitter: "https://x.com/hana_limbus" } },
        { cardId: 12, no: "XII", card: "The Hanged Man", char: { en: "Gregor", ko: "그레고르", ja: "グレゴール" }, artist: "Moth", pen: "Moth", role: { en: "Artist", ko: "일러스트레이터", ja: "イラストレーター" }, variantImage: "./images/AWduZSc.png", socials: { twitter: "https://x.com/moth_limbus" } },
        { cardId: 13, no: "XIII", card: "Death", char: { en: "Ryoshu", ko: "료슈", ja: "良秀" }, artist: "Ash", pen: "Ash", role: { en: "Artist", ko: "일러스트레이터", ja: "イラストレーター" }, variantImage: "./images/5lrFk3j.jpeg", socials: { twitter: "https://x.com/ash_limbus" } },
        { cardId: 14, no: "XIV", card: "Temperance", char: { en: "Rodion", ko: "로쟈", ja: "ロージャ" }, artist: "Nix", pen: "Nix", role: { en: "Artist", ko: "일러스트레이터", ja: "イラストレーター" }, variantImage: "./images/LLDHPbO.png", socials: { twitter: "https://x.com/nix_limbus" } },
        { cardId: 15, no: "XV", card: "The Devil", char: { en: "Kromer", ko: "크로머", ja: "クローマー" }, artist: "Void", pen: "Void", role: { en: "Artist", ko: "일러스트레이터", ja: "イラストレーター" }, variantImage: "./images/5TmkaRj.png", socials: { twitter: "https://x.com/void_limbus" } },
        { cardId: 16, no: "XVI", card: "The Tower", char: { en: "Outis", ko: "오티스", ja: "ウーティス" }, artist: "Grim", pen: "Grim", role: { en: "Artist", ko: "일러스트레이터", ja: "イラストレーター" }, variantImage: "./images/1dfh7kg.png", socials: { twitter: "https://x.com/grim_limbus" } },
        { cardId: 17, no: "XVII", card: "The Star", char: { en: "Demian", ko: "데미안", ja: "デミアン" }, artist: "Lux", pen: "Lux", role: { en: "Artist", ko: "일러스트레이터", ja: "イラストレーター" }, variantImage: "./images/LP9oHvK.png", socials: { twitter: "https://x.com/lux_limbus" } },
        { cardId: 18, no: "XVIII", card: "The Moon", char: { en: "Angela", ko: "앤젤라", ja: "アンジェラ" }, artist: "Pale", pen: "Pale", role: { en: "Artist", ko: "일러스트레이터", ja: "イラストレーター" }, variantImage: "./images/Q4sWYnn.png", socials: { twitter: "https://x.com/pale_limbus" } },
        { cardId: 19, no: "XIX", card: "The Sun", char: { en: "Carmen", ko: "카르멘", ja: "カルメン" }, artist: "Sol", pen: "Sol", role: { en: "Artist", ko: "일러스트레이터", ja: "イラストレーター" }, variantImage: "./images/96588.png", socials: { twitter: "https://x.com/sol_limbus" } },
        { cardId: 20, no: "XX", card: "Judgement", char: { en: "Binah", ko: "비나", ja: "ビナー" }, artist: "Arbiter", pen: "Arbiter", role: { en: "Artist", ko: "일러스트레이터", ja: "イラストレーター" }, variantImage: "./images/ZYC6CdH.png", socials: { twitter: "https://x.com/arbiter_limbus" } },
        { cardId: 21, no: "XXI", card: "The World", char: { en: "Ayin", ko: "아인", ja: "アイン" }, artist: "Manager", pen: "Manager", role: { en: "Artist", ko: "일러스트레이터", ja: "イラストレーター" }, variantImage: "./images/iimtseT.png", socials: { twitter: "https://x.com/manager_limbus" } }
    ],
    BRIEF_IMAGES: [
        { src: "./images/JtNx9pE.jpeg", key: "brief_fig_main" },
        { src: "./images/5m4k3Ur.jpeg", key: "brief_fig_a" },
        { src: "./images/q2jD7BO.jpeg", key: "brief_fig_b" },
        { src: "./images/49CqhCP.jpeg", key: "brief_fig_c" },
        { src: "./images/rEDw6E9.jpeg", key: "brief_fig_d" }
    ],
    EVENTS: [
        { time: '2026-02-15T11:30:00+09:00', id: 'countdown-1' },
        { time: '2026-02-21T12:00:00+09:00', id: 'countdown-2' }
    ]
};
